name: Status Checks

on:
  push:
    branches: [ v4 ]
  pull_request:
    branches: [ v4 ]
  workflow_dispatch:

jobs:
  tests:
    name: Evaluate on ${{ matrix.os }} with Godot ${{ matrix.godot_version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        godot_version: [ '4.1.3' , '4.2.1' ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: ${{ matrix.godot_version }}
          use-dotnet: false

      - name: Install addons
        run: godot --headless --script plug.gd install || true

      - name: Import files
        run: godot --headless --export-pack null /dev/null || true

      - name: Run unit tests
        run: godot --headless --script addons/gut/gut_cmdln.gd
